baseURL = 'https://laithsakka.github.io/devlogs-hugo-expr/'
ignoreFiles = ['README\\.md$']
languageCode = 'en-us'
title = 'PyTorch DevLog'

[params]
  description = 'Developer technical notes for PyTorch'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'

[taxonomies]
  tag = 'tags'

[menu]
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/pytorch/devlogs'
    weight = 10
